@echo off
echo Checking git status...
git status
echo.
echo Checkout frontend-update...
git checkout frontend-update || exit /b
echo.
echo Pulling latest frontend-update...
git pull origin frontend-update
echo.
echo Creating frontend-finish branch...
git checkout -b frontend-finish
echo.
echo Merging frontend-role...
git merge frontend-role
echo.
echo Verifying branches...
git branch
